import { 
  Injectable, 
  Logger, 
  NotFoundException, 
  BadRequestException, 
  ConflictException,
  ForbiddenException,
  InternalServerErrorException 
} from '@nestjs/common';
import { InjectModel } from '@nestjs/sequelize';
import { Op } from 'sequelize';
import { v4 as uuidv4 } from 'uuid';
import * as bcrypt from 'bcrypt';

// Entities
import { Tenant, TenantStatus } from './entities/tenant.entity';
import { UserTenant, UserTenantRole, UserTenantStatus } from './entities/user-tenant.entity';
import { User, UserRole } from '../users/entities/user.entity';

// DTOs
import { CreateTenantDto } from './dto/create-tenant.dto';
import { UpdateTenantDto } from './dto/update-tenant.dto';

// Services
import { TenantDatabaseService } from './tenant-database.service';

@Injectable()
export class TenantsService {
  private readonly logger = new Logger(TenantsService.name);

  constructor(
    @InjectModel(Tenant) private tenantModel: typeof Tenant,
    @InjectModel(UserTenant) private userTenantModel: typeof UserTenant,
    @InjectModel(User) private userModel: typeof User,
    private tenantDatabaseService: TenantDatabaseService,
  ) {}

  /**
   * Create a new tenant (only SuperAdmin can do this)
   */
  async createTenant(createTenantDto: CreateTenantDto, createdByUserId: number): Promise<Tenant> {
    try {
      // Check if tenant name is available
      const existingName = await this.tenantModel.findOne({
        where: { name: createTenantDto.name }
      });
      if (existingName) {
        throw new ConflictException('Tenant name already exists');
      }

      // Check if email is available (must be unique for tenant authentication)
      const existingEmail = await this.tenantModel.findOne({
        where: { contactEmail: createTenantDto.email }
      });
      if (existingEmail) {
        throw new ConflictException('A tenant with this email already exists');
      }

      // Auto-generate subdomain from name
      const autoGeneratedSubdomain = Tenant.sanitizeName(createTenantDto.name);
      
      // Check if subdomain is available
      const existingSubdomain = await this.tenantModel.findOne({
        where: { subdomain: autoGeneratedSubdomain }
      });
      if (existingSubdomain) {
        throw new ConflictException('A tenant with a similar name already exists. Please choose a different name.');
      }

      // Check if the database name that would be generated is available
      const proposedDatabaseName = Tenant.generateDatabaseName(createTenantDto.name);
      const existingDatabaseName = await this.tenantModel.findOne({
        where: { databaseName: proposedDatabaseName }
      });
      if (existingDatabaseName) {
        throw new ConflictException('A tenant with a similar name already exists. Please choose a different name.');
      }

      // Hash the password
      const saltRounds = 10;
      const password_hash = await bcrypt.hash(createTenantDto.password, saltRounds);

      // Generate tenant key and database name explicitly
      const tenantKey = `tenant_${uuidv4().replace(/-/g, '').substring(0, 16)}`;

      // Create the tenant with credentials
      const tenant = await this.tenantModel.create({
        name: createTenantDto.name,
        description: createTenantDto.description,
        password_hash: password_hash,
        subdomain: autoGeneratedSubdomain,
        tenantKey: tenantKey,
        databaseName: proposedDatabaseName,
        contactEmail: createTenantDto.email,
        contactPhone: createTenantDto.phone,
        age: createTenantDto.age,
        address: createTenantDto.address,
        status: TenantStatus.PENDING_SETUP,
      } as any);

      // Create tenant database
      try {
        await this.tenantDatabaseService.createTenantDatabase(
          tenant.tenantKey,
          tenant.databaseName
        );
        this.logger.log(`Tenant database created successfully for: ${tenant.name}`);
      } catch (dbError) {
        this.logger.warn(`Failed to create tenant database for ${tenant.name}:`, dbError);
        // Continue with tenant creation even if database creation fails
        // The database can be created later manually
      }

      // Update tenant status to ACTIVE regardless of database creation status
      await tenant.update({ status: TenantStatus.ACTIVE });
      await tenant.updateUserCount();

      this.logger.log(`Tenant created successfully: ${tenant.name} by user ${createdByUserId}`);
      
      return tenant;
    } catch (error) {
      this.logger.error('Error creating tenant:', error);
      throw error;
    }
  }

  /**
   * Get all tenants (SuperAdmin only)
   */
  async findAll(page: number = 1, limit: number = 10): Promise<{
    tenants: Tenant[];
    total: number;
    currentPage: number;
    totalPages: number;
  }> {
    const offset = (page - 1) * limit;

    const { rows: tenants, count: total } = await this.tenantModel.findAndCountAll({
      limit,
      offset,
      include: [
        {
          model: User,
          as: 'adminUser',
          attributes: ['id', 'name', 'email'],
        },
      ],
      order: [['createdAt', 'DESC']],
    });

    return {
      tenants,
      total,
      currentPage: page,
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Get a specific tenant by ID
   */
  async findOne(id: number): Promise<Tenant> {
    const tenant = await this.tenantModel.findByPk(id, {
      include: [
        {
          model: User,
          as: 'adminUser',
          attributes: ['id', 'name', 'email', 'phone'],
        },
        {
          model: UserTenant,
          include: [
            {
              model: User,
              attributes: ['id', 'name', 'email'],
            },
          ],
        },
      ],
    });

    if (!tenant) {
      throw new NotFoundException('Tenant not found');
    }

    return tenant;
  }

  /**
   * Get tenant by subdomain
   */
  async findBySubdomain(subdomain: string): Promise<Tenant> {
    const tenant = await this.tenantModel.findOne({
      where: { subdomain },
      include: [
        {
          model: User,
          as: 'adminUser',
          attributes: ['id', 'name', 'email'],
        },
      ],
    });

    if (!tenant) {
      throw new NotFoundException('Tenant not found');
    }

    return tenant;
  }

  /**
   * Get tenants for a specific user
   */
  async findTenantsForUser(userId: number): Promise<{
    tenants: Array<Tenant & { userTenant: UserTenant }>;
    activeTenants: number;
  }> {
    const userTenants = await this.userTenantModel.findAll({
      where: { userId },
      include: [
        {
          model: Tenant,
          where: { status: TenantStatus.ACTIVE },
        },
      ],
    });

    const tenants = userTenants.map(ut => ({
      ...ut.tenant.get({ plain: true }),
      userTenant: ut.get({ plain: true }),
    })) as any;

    return {
      tenants,
      activeTenants: tenants.length,
    };
  }

  /**
   * Update a tenant
   */
  async update(id: number, updateTenantDto: UpdateTenantDto, updatedByUserId: number): Promise<Tenant> {
    const tenant = await this.findOne(id);

    // Check if name is being changed and validate implications
    if (updateTenantDto.name && updateTenantDto.name !== tenant.name) {
      // Check if tenant name is available
      const existingName = await this.tenantModel.findOne({
        where: { 
          name: updateTenantDto.name,
          id: { [Op.ne]: id }
        }
      });
      if (existingName) {
        throw new ConflictException('Tenant name already exists');
      }

      // Auto-generate new subdomain from new name
      const newSubdomain = Tenant.sanitizeName(updateTenantDto.name);
      
      // Check if the new subdomain would conflict
      const existingSubdomain = await this.tenantModel.findOne({
        where: { 
          subdomain: newSubdomain,
          id: { [Op.ne]: id }
        }
      });
      if (existingSubdomain) {
        throw new ConflictException('A tenant with a similar name already exists. Please choose a different name.');
      }

      // Check if the new database name would conflict
      const proposedDatabaseName = Tenant.generateDatabaseName(updateTenantDto.name);
      const existingDatabaseName = await this.tenantModel.findOne({
        where: { 
          databaseName: proposedDatabaseName,
          id: { [Op.ne]: id }
        }
      });
      if (existingDatabaseName) {
        throw new ConflictException('A tenant with a similar name already exists. Please choose a different name.');
      }

      this.logger.warn(`Tenant name changed from "${tenant.name}" to "${updateTenantDto.name}". Database name will be updated to "${proposedDatabaseName}" but actual MySQL database "${tenant.databaseName}" will not be renamed automatically.`);
    }

    // Update the tenant
    await tenant.update(updateTenantDto);

    // If name was changed, update the subdomain and database name
    if (updateTenantDto.name && updateTenantDto.name !== tenant.name) {
      const newSubdomain = Tenant.sanitizeName(updateTenantDto.name);
      const newDatabaseName = Tenant.generateDatabaseName(updateTenantDto.name);
      await tenant.update({ 
        subdomain: newSubdomain,
        databaseName: newDatabaseName 
      });
    }

    this.logger.log(`Tenant updated: ${tenant.name} by user ${updatedByUserId}`);
    return await this.findOne(id);
  }

  /**
   * Soft delete a tenant
   */
  async remove(id: number, deletedByUserId: number): Promise<void> {
    const tenant = await this.findOne(id);
    
    // Set tenant status to inactive first
    await tenant.update({ status: TenantStatus.INACTIVE });
    
    // Soft delete the tenant
    await tenant.destroy();

    // Close tenant database connection
    await this.tenantDatabaseService.closeTenantConnection(tenant.tenantKey);

    this.logger.log(`Tenant deleted: ${tenant.name} by user ${deletedByUserId}`);
  }

  /**
   * Get users associated with a tenant
   */
  async getTenantUsers(
    tenantId: number, 
    page: number = 1, 
    limit: number = 10
  ): Promise<{
    users: Array<User & { userTenant: UserTenant }>;
    total: number;
    currentPage: number;
    totalPages: number;
  }> {
    const tenant = await this.findOne(tenantId);
    const offset = (page - 1) * limit;

    const { rows: userTenants, count: total } = await this.userTenantModel.findAndCountAll({
      where: { tenantId },
      limit,
      offset,
      include: [
        {
          model: User,
          attributes: ['id', 'name', 'email', 'phone', 'createdAt'],
        },
      ],
      order: [['createdAt', 'DESC']],
    });

    const users = userTenants.map(ut => ({
      ...ut.user.get({ plain: true }),
      userTenant: ut.get({ plain: true }),
    })) as any;

    return {
      users,
      total,
      currentPage: page,
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Add a user to a tenant
   */
  async addUserToTenant(
    tenantId: number, 
    userId: number, 
    role: UserTenantRole = UserTenantRole.MEMBER,
    addedByUserId: number
  ): Promise<UserTenant> {
    const tenant = await this.findOne(tenantId);
    const user = await this.userModel.findByPk(userId);

    if (!user) {
      throw new NotFoundException('User not found');
    }

    // Check if user is already associated with this tenant
    const existingAssociation = await this.userTenantModel.findOne({
      where: { userId, tenantId }
    });

    if (existingAssociation) {
      throw new ConflictException('User is already associated with this tenant');
    }

    // Check tenant user limits
    if (!tenant.canInviteUsers()) {
      throw new BadRequestException('Tenant has reached maximum user limit or is not active');
    }

    // Create the association
    const userTenant = await this.userTenantModel.create({
      userId,
      tenantId,
      role,
      status: UserTenantStatus.ACTIVE,
      joinedAt: new Date(),
    } as any);

    // Update tenant user count
    await tenant.updateUserCount();

    this.logger.log(`User ${userId} added to tenant ${tenantId} by user ${addedByUserId}`);
    return userTenant;
  }

  /**
   * Remove a user from a tenant
   */
  async removeUserFromTenant(
    tenantId: number, 
    userId: number, 
    removedByUserId: number
  ): Promise<void> {
    const userTenant = await this.userTenantModel.findOne({
      where: { userId, tenantId }
    });

    if (!userTenant) {
      throw new NotFoundException('User is not associated with this tenant');
    }

    // Can't remove the tenant admin
    if (userTenant.role === UserTenantRole.ADMIN) {
      throw new BadRequestException('Cannot remove tenant administrator');
    }

    await userTenant.destroy();

    // Update tenant user count
    const tenant = await this.findOne(tenantId);
    await tenant.updateUserCount();

    this.logger.log(`User ${userId} removed from tenant ${tenantId} by user ${removedByUserId}`);
  }

  /**
   * Update user role in tenant
   */
  async updateUserTenantRole(
    tenantId: number, 
    userId: number, 
    newRole: UserTenantRole, 
    updatedByUserId: number
  ): Promise<UserTenant> {
    const userTenant = await this.userTenantModel.findOne({
      where: { userId, tenantId }
    });

    if (!userTenant) {
      throw new NotFoundException('User is not associated with this tenant');
    }

    await userTenant.update({ role: newRole });

    this.logger.log(`User ${userId} role updated to ${newRole} in tenant ${tenantId} by user ${updatedByUserId}`);
    return userTenant;
  }

  /**
   * Get tenant statistics
   */
  async getTenantStats(tenantId: number): Promise<{
    userCount: number;
    activeUsers: number;
    pendingInvitations: number;
    lastActivity: Date | null;
  }> {
    const tenant = await this.findOne(tenantId);

    const userStats = await this.userTenantModel.findAll({
      where: { tenantId },
      attributes: ['status', 'lastAccessAt'],
    });

    const activeUsers = userStats.filter(ut => ut.status === UserTenantStatus.ACTIVE).length;
    const lastActivity = userStats.reduce((latest, ut) => {
      if (ut.lastAccessAt && (!latest || ut.lastAccessAt > latest)) {
        return ut.lastAccessAt;
      }
      return latest;
    }, null as Date | null);

    // TODO: Get pending invitations count when TenantInvitationService is implemented
    const pendingInvitations = 0;

    return {
      userCount: tenant.userCount,
      activeUsers,
      pendingInvitations,
      lastActivity,
    };
  }

  /**
   * Check if user has permission to perform action on tenant
   */
  async checkUserPermission(
    userId: number, 
    tenantId: number, 
    permission: keyof NonNullable<UserTenant['permissions']>
  ): Promise<boolean> {
    const userTenant = await this.userTenantModel.findOne({
      where: { userId, tenantId, status: UserTenantStatus.ACTIVE }
    });

    if (!userTenant) {
      return false;
    }

    return userTenant.hasPermission(permission);
  }

  /**
   * Get user's role in tenant
   */
  async getUserTenantRole(userId: number, tenantId: number): Promise<UserTenant | null> {
    return await this.userTenantModel.findOne({
      where: { userId, tenantId }
    });
  }

  /**
   * Manually activate a tenant
   */
  async activateTenant(id: number, activatedByUserId: number): Promise<Tenant> {
    const tenant = await this.findOne(id);
    
    if (tenant.status === TenantStatus.ACTIVE) {
      return tenant; // Already active
    }

    // Update tenant status to ACTIVE
    await tenant.update({ status: TenantStatus.ACTIVE });
    await tenant.updateUserCount();

    this.logger.log(`Tenant manually activated: ${tenant.name} by user ${activatedByUserId}`);
    return tenant;
  }

  /**
   * Assign a user as tenant admin
   */
  async assignTenantAdmin(tenantId: number, userId: number, assignedByUserId: number): Promise<Tenant> {
    const tenant = await this.findOne(tenantId);
    const user = await this.userModel.findByPk(userId);

    if (!user) {
      throw new NotFoundException('User not found');
    }

    // Add user to tenant as admin if not already associated
    const existingAssociation = await this.userTenantModel.findOne({
      where: { userId, tenantId }
    });

    if (!existingAssociation) {
      await this.addUserToTenant(tenantId, userId, UserTenantRole.ADMIN, assignedByUserId);
    } else if (existingAssociation.role !== UserTenantRole.ADMIN) {
      // Update existing association to admin role
      await existingAssociation.update({ role: UserTenantRole.ADMIN });
    }

    // Update tenant admin user ID
    await tenant.update({ adminUserId: userId });

    this.logger.log(`User ${userId} assigned as admin for tenant ${tenantId} by user ${assignedByUserId}`);
    return await this.findOne(tenantId);
  }

  /**
   * Clear all tenants (SuperAdmin only - use with extreme caution)
   */
  async clearAllTenants(deletedByUserId: number): Promise<{ deletedCount: number; deletedTenants: string[] }> {
    try {
      // Get all tenants first
      const tenants = await this.tenantModel.findAll({
        attributes: ['id', 'name', 'tenantKey', 'databaseName'],
      });

      const deletedTenants: string[] = [];
      let deletedCount = 0;

      // Delete each tenant
      for (const tenant of tenants) {
        try {
          // Set status to inactive
          await tenant.update({ status: TenantStatus.INACTIVE });
          
          // Close database connection
          await this.tenantDatabaseService.closeTenantConnection(tenant.tenantKey);
          
          // Soft delete the tenant
          await tenant.destroy();
          
          deletedTenants.push(tenant.name);
          deletedCount++;
          
          this.logger.log(`Tenant deleted: ${tenant.name} during bulk clear operation`);
        } catch (error) {
          this.logger.error(`Failed to delete tenant ${tenant.name}:`, error);
          // Continue with other tenants even if one fails
        }
      }

      this.logger.log(`Bulk tenant deletion completed: ${deletedCount} tenants deleted by user ${deletedByUserId}`);
      
      return {
        deletedCount,
        deletedTenants,
      };
    } catch (error) {
      this.logger.error('Error during bulk tenant deletion:', error);
      throw error;
    }
  }

  /**
   * Create multiple tenants at once (SuperAdmin only)
   */
  async createMultipleTenants(
    tenantData: CreateTenantDto[], 
    createdByUserId: number
  ): Promise<{ 
    created: Tenant[]; 
    failed: Array<{ data: CreateTenantDto; error: string }>;
    summary: { successful: number; failed: number; total: number };
  }> {
    const created: Tenant[] = [];
    const failed: Array<{ data: CreateTenantDto; error: string }> = [];

    for (const tenantDto of tenantData) {
      try {
        const tenant = await this.createTenant(tenantDto, createdByUserId);
        created.push(tenant);
      } catch (error) {
        failed.push({
          data: tenantDto,
          error: error.message || 'Unknown error occurred'
        });
        this.logger.error(`Failed to create tenant ${tenantDto.name}:`, error);
      }
    }

    const summary = {
      successful: created.length,
      failed: failed.length,
      total: tenantData.length
    };

    this.logger.log(`Bulk tenant creation completed: ${summary.successful}/${summary.total} successful by user ${createdByUserId}`);

    return {
      created,
      failed,
      summary
    };
  }
} 